name: smart_store
description: "Smart Store - manage your business by modern system"
publish_to: 'none' 

version: 4.2.2+1

environment:
  sdk: ^3.11.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^4.12.1
  firebase_auth: ^6.5.6
  shared_preferences: ^2.5.5
  cloud_firestore: ^6.7.1
  easy_localization: ^3.0.7
  device_info_plus: ^13.2.0
  http: ^1.6.0
  crypto: ^3.0.6
  url_launcher: ^6.3.1
  fl_chart: ^0.70.2
  intl: ^0.20.2
  animated_theme_switcher: ^2.0.10
  bcrypt: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^6.0.0

flutter:

  assets:
    - assets/logo.png
    - assets/shopping_cart.png
    - assets/shopping_cart_dark.png

    - assets/translations/

  uses-material-design: true