// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcm6ukUmZRHdp7qQYkfyH41VXlvMq6eaI',
    appId: '1:282827813787:ios:05e8d8b2c560908ebe273e',
    messagingSenderId: '282827813787',
    projectId: 'smart-store-7d83e',
    databaseURL: 'https://smart-store-7d83e-default-rtdb.firebaseio.com',
    storageBucket: 'smart-store-7d83e.firebasestorage.app',
    iosBundleId: 'com.example.smartStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBojcEoKjfyU0uq-uBJ5ldf6MVgzt8py9U',
    appId: '1:282827813787:web:cd843cfbc3e3c9e5be273e',
    messagingSenderId: '282827813787',
    projectId: 'smart-store-7d83e',
    authDomain: 'smart-store-7d83e.firebaseapp.com',
    databaseURL: 'https://smart-store-7d83e-default-rtdb.firebaseio.com',
    storageBucket: 'smart-store-7d83e.firebasestorage.app',
    measurementId: 'G-1Q3LJH9DH1',
  );
}
